import type { Metadata } from "next";
import "./globals.css";
import "react-quill/dist/quill.snow.css";
import { Providers } from "../components/provider";
import { Toaster } from "react-hot-toast";
import { Nav } from "@/components/nav";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Best laptops store in the town",
  description: "Generated by create next app",
  icons: "_next/image?url=%2Flogo.png&w=64&q=75",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="light">
      <body>
        <Providers>
          <Nav />
          <main className="w-full max-w-7xl mx-auto max-md:px-3">
            {children}
          </main>
          <Footer />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
